### ISSUE TITLE
Analytics - Measure the performance of referrals from YorubaBible.net to DaBible

### ISSUE THREAD

**Issue by sanmiayotunde** [sanmiayotunde/DaBible-Foundation#11]
1. Visit Google Analytics https://analytics.google.com/analytics/web/#/report/trafficsources-all-traffic/a83855944w180962096p178958508/_u.date00=20210124&_u.date01=20210130

- [ ] Change the date to Feb 7 2021 - Feb 14 2021
- [ ] Check the number of referrals coming from YorubaBible.net to DaBible.com

Due Date: Feb 14 2021

**Comment by emmanlex** [comment]
At present we have had a total of 6 referrals dated from Feb 7 to Feb 9, compared to last week's report dated from Jan 31 to Feb 6 (which only had 8 referrals) we have only two less. We can assume that there will likely be more referrals by Feb 14 and expect an increase in our traffic. 
![referrals](https://user-images.githubusercontent.com/50557337/107404270-ba36f000-6acb-11eb-8158-dedf76bef77e.png)

**Comment by emmanlex** [comment]
I followed the directions you provided and was able to see an increase in the number of users since the redirection was put in place. I also looked up the subsequent week, Feb 14 - Feb 20  there was no actual increase but the neither was there a decrease.   
![Uploading Screen Shot 2021-02-25 at 3.36.24 PM.png…]()
![Screen Shot 2021-02-25 at 3 51 22 PM](https://user-images.githubusercontent.com/50557337/109224290-5fff8580-7781-11eb-9222-facb19a3a346.png)
